# Generated by Django 4.2.6 on 2024-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес доставки'),
        ),
    ]
