# Generated by Django 4.2.6 on 2024-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('id_input', models.CharField(max_length=100, verbose_name='Id для Input')),
                ('value', models.CharField(choices=[('name', 'name'), ('-name', '-name'), ('price', 'price'), ('-price', '-price'), ('brand', 'brand'), ('-brand', '-brand')], max_length=70, verbose_name='Параметр фильтрации')),
                ('is_have', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='Указывать в процентах', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_memory',
            field=models.CharField(blank=True, choices=[('64гб', '64гб'), ('128гб', '128гб'), ('256гб', '256гб'), ('512гб', '512гб'), ('1тб', '1тб')], max_length=30, verbose_name='Память смартфона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
