# Generated by Django 4.2.6 on 2024-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_filter_product_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter_product',
            options={'ordering': ('id',), 'verbose_name': 'Фильтрация товаров', 'verbose_name_plural': 'Фильтраци товаров'},
        ),
        migrations.AlterField(
            model_name='filter_product',
            name='id_input',
            field=models.CharField(default='flexRadioDefault2', max_length=100, unique=True, verbose_name='Id для Input'),
        ),
        migrations.AlterField(
            model_name='filter_product',
            name='value',
            field=models.CharField(choices=[('name', 'name'), ('-name', '-name'), ('price', 'price'), ('-price', '-price'), ('brand_id', 'brand_id'), ('-brand_id', '-brand_id')], max_length=70, verbose_name='Параметр фильтрации'),
        ),
    ]
