# Generated by Django 4.2.6 on 2024-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_filter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=50, null=True, verbose_name='Количество'),
        ),
    ]
