# Generated by Django 4.2.6 on 2024-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='quantity',
            field=models.CharField(default=1, editable=False, verbose_name='Количество'),
        ),
    ]
