# Generated by Django 4.2.6 on 2024-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comments_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Количество'),
        ),
    ]
