# Generated by Django 4.2.6 on 2024-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comments_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, max_length=5, verbose_name='Оценка'),
        ),
    ]
